<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Hikyaku.MCP.Server</RootNamespace>
    <ImplicitUsings>true</ImplicitUsings>
    <Authors>Paolo Possanzini</Authors>
    <Description>MCP extensions for Hikyaku</Description>
    <Copyright>Copyright Paolo Possanzini</Copyright>
    <Features>strict</Features>
    <PackageTags>mediator;request;response;queries;commands;notifications;rpc;rabbitmq</PackageTags>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Deterministic>true</Deterministic>
    <PackageIcon>Logo-128.png</PackageIcon>
    <RepositoryUrl>https://github.com/ppossanzini/Hikyaku</RepositoryUrl>
    <PackageId>Hikyaku.MCP.Server</PackageId>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\..\Hikyaku.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hikyaku" Version="[9.5.1,]"/>
    <PackageReference Include="Hikyaku.MCP.Contracts" Version="[9.5.2,]"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\assets\Logo-128.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
      <Link>Logo-128.png</Link>
    </None>
    <None Include="..\..\..\Hikyaku.snk">
      <Link>Hikyaku.snk</Link>
    </None>
  </ItemGroup>
  
</Project>
